# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Misol Kim
tagline:          'CV'
description:      'Application Developer'
url:              https://kim-misol.github.io/
baseurl:          /

author:
  name:           'Misol'
  url:            ""

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/kim-misol/
